# Generated by Django 4.0.5 on 2022-06-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_images_images_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='photos/products/vendor/'),
        ),
    ]
