# Generated by Django 4.0.5 on 2022-06-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(default=1, upload_to='photos/products/vendors/mandatory'),
            preserve_default=False,
        ),
    ]
