# Generated by Django 4.0.5 on 2022-07-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_primary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unlisted_by',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
