# Generated by Django 4.0.5 on 2022-07-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_unlisted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carousel',
            name='is_top',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
