# Generated by Django 4.0.5 on 2022-07-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_variationsample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationSample',
        ),
    ]
