# Generated by Django 4.0.5 on 2022-07-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_variationsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationsample',
            name='type',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
