# Generated by Django 4.0.5 on 2022-07-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='vendor_req_rejection_status',
            field=models.BooleanField(default=False),
        ),
    ]
