# Generated by Django 4.0.5 on 2022-07-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_vendor_req_rejection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
