# Generated by Django 4.0.5 on 2022-07-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_sub_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='category',
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='sub_category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
