# Generated by Django 4.0.5 on 2022-07-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_is_saved_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='order_product_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
